using System;
using System.Collections.Generic;
using System.Text;

namespace DevIO.Business.Models
{
    public enum Sistema
    {
        NortesysERPCompany = 001,
        NortesysMobileDistribuidora = 002,
        NortesysMobileBalcao = 003,
        DTEFDirecao = 004,
        TEFDiscado = 005,
        TEFIP = 006,
        SitefTefDedicado = 007,
        SCACallCenter = 008,
        NortesysEmissorNFe = 009,
        NortesysPonto = 010,
        NortesysFrentedeLoja = 011,
        NortesysSPEDContabil = 012,
        NortesysOSECF = 013,
        NortesysPraticusCard = 014,
        SaberGestaoEscolar = 015,
        NortesysiXML = 016,
        AUTONFe1000 = 017,
        NortesysERPOffice = 018,
        NortesysERPFarma = 019,
        NortesysFarmaciaPopular = 020,
        NortesysSNGPC = 021,
        NotaFiscalPaulista = 022,
        NortesysBoletos = 023,
        AssessorContabilExcel = 024,
        ExporteImport = 025,
        NORTESYSClinic = 026,
        NortesysContador = 027,
        IntegradorApogeusForcadeVendas = 028,
        NortesysERPEmissorPAFOffice = 029,
        NortesysERPBalcao = 030,
        NortesysERPEmissorPAFFarma = 031,
        NORTESYSDante = 032,
        NortesysMDe = 033,
        inCRM = 034,
        AtualizadorNortesys = 035,
        NortesysIndustria = 036,
        GerenciadordeNFe = 037,
        NortesysERPCompany_projetopiloto = 038,
        NortesysFrentedeLoja_projetopiloto = 039,
        NortesysERPEmissorPAFECFDAVePREVENDA_projetopiloto = 040,
        ServidordeLicencas = 041,
        NortesysNFeComplementar = 042,
        NortesysCADECF = 043,
        NotaFiscalSergipana = 044,
        NortesysSEF = 045,
        SisconsultaSistemadeAutoAtendimento = 046,
        Liberadorinternodelicencas = 047,
        ConsultaPreco = 048,
        ImpressorNFeNortesys = 049,
        NortesysClinicFinanceiro = 050,
        NORTESYSGerenciadorRelatorio = 075,
        NORTESYSFinanceiro = 050,
        NORTESYSEstoque = 051,
        NortesysERPFacility = 052,
        NortesysSPED = 053,
        NortesysNFCe = 054,
        SincronizadordeVendasOffline = 055,
        NortesysTreinamentoFrentedeLoja = 056,
        NortesysERPCompanyNFeNFCeNFSeiXMLSPEDMDeMDFeCTe = 057,
        KitERPCompanyiXMLSPEDNFeMDeBoletos = 58,
        NortesysERPOfficeNFeNFCeNFSeiXMLSPEDMDeMDFeCTe = 059,
        KitERPOfficeiXMLSPEDNFeMDeBoletos = 060,
        ECFNacional = 061,
        NortesysERPFarmaSNGPCFPopNFeNFCeiXMLSPEDMDeMDFe = 062,
        KitERPFarmaiXMLSPEDNFeMDeBoletos = 063,
        NortesysSERVICONT = 064,
        Treinamentoconsultoria = 065,
        Consultoriaemgestaoempresarial = 066,
        Assessoriaemgestaoempresarial = 067,
        NortesysImport = 068,
        NortesysGNRE = 069,
        NortesysNFSe = 070,
        NortesysERPAgroNFeNFCeNFSeiXMLSPEDMDeMDFeCTe = 071,
        NortesysERPFacilityNFeNFCeNFSeiXMLSPEDMDeMDFeCTe = 072,
        NortesysMDFe = 073,
        NortesysPosvendaControledeQualidade = 074,
        GerenciadorderelatoriosStimulsoft = 075,
        CDFConexaoDigitalFiscalTocantins = 076,
        NortesysERPCorporation = 077,
        NortesysImpressorRestaurante = 078,
        NortesysVerificadorNFCe = 079,
        Dotsmart = 080,
        NortesysCTe = 081,
        Sincronizadorforcadevendas = 082,
        NORTESYSSincronizadorPricerERP = 083,
        NORTESYSSincronizadorXTechCommerceERP = 085,
        NORTESYSConnectSerasaExperian = 086,
        ProdutoNortesys
    }
}